Convert exported requirements to constraints format (#308)
* test: Use Poetry 1.0 compatible lock file in test data

* test: Run tests againsts Poetry 1.0 as well

* test: Fix missing subdependencies in Project.dependencies

* test: Replace list_packages fixture by a plain function

* test: Replace run_nox_with_noxfile fixture by plain function

* test: Remove unused fixture run_nox

* test: Remove unused fixture write_noxfile

* style: Reformat test_functional

* test: Handle URL and path dependencies in list_packages fixture

* test: Handle URL dependencies in Project.get_dependency

* test: Add test data for URL dependencies

* test: Add functional test for URL dependencies

Add a failing test for URL dependencies.

Test output below:

  nox > Command python -m pip install
  --constraint=.nox/test/tmp/requirements.txt
  file:///…/url-dependency/dist/url_dependency-0.1.0-py3-none-any.whl failed
  with exit code 1:

  DEPRECATION: Constraints are only allowed to take the form of a package name
  and a version specifier. Other forms were originally permitted as an accident
  of the implementation, but were undocumented. The new implementation of the
  resolver no longer supports these forms. A possible replacement is replacing
  the constraint with a requirement.. You can find discussion regarding this at
  https://github.com/pypa/pip/issues/8210.

  ERROR: Links are not allowed as constraints

* build: Add dependency on packaging >= 20.9

* refactor(poetry): Do not write exported requirements to disk

* fix: Convert exported requirements to constraints format

* test: Add unit tests for to_constraints

* test: Use canonicalize_name from packaging.utils

* test: Add test data for path dependencies

* test: Add functional test for path dependency

* test: Mark test for path dependencies as XFAIL